import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Document, Page } from "react-pdf";
import { PlayIcon, DocumentTextIcon } from "@heroicons/react/outline";
import LanguageDropdown from "@/components/LanguageDropdown";
import axios from "axios";
import { transcript } from "data/transcript";
import TextLoadingSkeleton from "@/components/TextLoadingSkeleton";

export default function Home() {
  const [language, setLanguage] = useState({
    name: "English",
    svg: "https://lipis.github.io/flag-icon-css/flags/4x3/us.svg",
    code: "en",
  });

  const [outputLoading, setOutputLoading] = useState(false);
  const [englishTranscript, setEnglishTranscript] = useState(transcript);
  const [episodeTranscript, setEpisodeTranscript] = useState(transcript);
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  useEffect(() => {
    if (language.code === "en") {
      setEpisodeTranscript(englishTranscript);
      return;
    }

    setOutputLoading(true);

    axios
      .post(`/api/proxy?proxyRoute=translator`, {
        from: "en",
        to: language.code,
        text: englishTranscript,
      })
      .then(async (response) => {
        const data = response.data;
        setEpisodeTranscript(data.result);
        setOutputLoading(false);
      });
  }, [language]);

  return (
    <div className='bg-white'>
      <Head>
        <title>Signabled</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='pt-36 max-w-screen-2xl mx-auto px-12'>
        <div className='w-full flex flex-col lg:flex-row'>
          <div className='w-full lg:w-5/12'>
            <h1 className='text-left text-3xl text-blue-800 font-bold mb-4'>
              PDF Preview
            </h1>
            <div className='relative'>
              <Document
                file='./example.pdf'
                options={{ workerSrc: "/pdf.worker.js" }}
                onLoadSuccess={onDocumentLoadSuccess}>
                <Page pageNumber={pageNumber} />
              </Document>

              <div className='absolute top-0 -right-12'>
                <div className='flex items-start flex-row space-x-4'>
                  <button className='inline-flex items-center px-6 py-2 bg-blue-600 rounded-sm text-white font-medium border-none focus:outline-none hover:bg-blue-700 shadow-lg text-sm focus:ring ring-blue-600 ring-offset-2'>
                    <PlayIcon className='w-6 h-6 mr-1' />
                    Listen
                  </button>
                  <button className='inline-flex items-center px-6 py-2 bg-green-600 rounded-sm text-white font-medium border-none focus:outline-none hover:bg-green-700 shadow-lg text-sm focus:ring ring-green-600 ring-offset-2'>
                    <DocumentTextIcon className='w-6 h-6 mr-1' />
                    Summarize
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className='h-full w-full lg:w-6/12 ml-auto'>
            <div className='flex flex-row items-between justify-between mb-4'>
              <h1 className='text-left text-3xl text-blue-800 font-bold mb-4'>
                Output
              </h1>
              <LanguageDropdown selected={language} setSelected={setLanguage} />
            </div>
            {outputLoading ? (
              <TextLoadingSkeleton />
            ) : (
              <textarea
                readOnly
                value={episodeTranscript}
                className='flex items-center justify-center rounded-lg w-full h-96 border-4 border-blue-600 focus:border-blue-700 focus:outline-none pb-2 px-4 text-md text-base leading-relaxed text-gray-700'
                type='text'
              />
            )}

            <div className='mt-4 ring-offset-4 inline-flex items-center text-base text-gray-600 font-md font-medium'>
              Waiver Document for the{" "}
              <img className='h-4 ml-2' src='./aapd.png' alt='AAPD' />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
